"""
Neutral, deterministic security scanner (Phase 2 SoD — Step 2).

Extracted out of agents/coder_agent.py so the security-scan logic does NOT
live in a coder-owned module. The Independent Verifier subprocess owns
verification execution; the scanner it runs must be usable by the verifier
boundary without importing coder implementation. This module is pure and
side-effect free: it maps {path: content} -> (ok, findings).

Language-aware since P5: JVM files (.java/.kt/.scala) are checked against
JVM dynamic-execution / raw-deserialization patterns; everything else
against the Python patterns.

This is a MECHANICAL extraction — the scan rules and behavior are unchanged
from agents/coder_agent.py. Do NOT redesign the scanner here.
"""

import re

# Patterns that have no business in an offline stdlib-only CLI tool.
# NOTE: plain open(path, 'w') is legitimate (the store file) and must
# NOT be flagged — v0 of this scanner did and produced a false positive.
_DANGEROUS_PY = re.compile(
    r"\b(eval|exec|compile)\s*\(|\bos\.system\b|\bsubprocess\.\w*shell\b"
    r"|\bsocket\.(socket|create_connection)\b|\bpickle\.loads?\b"
    r"|\b__import__\s*\(", re.MULTILINE)

# P5: Java/Kotlin sources were previously scanned with the Python
# patterns verbatim, which matched nothing useful. These are the
# equivalent dynamic-execution / raw-deserialization red flags for JVM
# code generated by the Spring Boot coder agent.
_DANGEROUS_JVM = re.compile(
    r"\bRuntime\s*\.\s*getRuntime\s*\(\s*\)\s*\.\s*exec"
    r"|\bnew\s+ProcessBuilder\b|\bClass\s*\.\s*forName\s*\("
    r"|\bsun\.misc\.Unsafe\b|\bObjectInputStream\b"
    r"|\bXMLDecoder\b", re.MULTILINE)

_SCAN_RULES: tuple[tuple[tuple[str, ...], "re.Pattern[str]"], ...] = (
    ((".java", ".kt", ".scala"), _DANGEROUS_JVM),
)


def _pattern_for(path: str) -> "re.Pattern[str]":
    for extensions, pattern in _SCAN_RULES:
        if path.endswith(extensions):
            return pattern
    return _DANGEROUS_PY


def security_scan(files: dict[str, str]) -> tuple[bool, list[str]]:
    """
    Real (if naive) offline scan: the generated source is inspected for
    dynamic-execution / shell / raw-socket patterns. Evidence comes from
    this function's output, never from an LLM's self-assessment.
    """
    findings = []
    for path, content in files.items():
        pattern = _pattern_for(path)
        for i, line in enumerate(content.splitlines(), 1):
            if line.lstrip().startswith("#"):
                continue
            if pattern.search(line):
                findings.append(f"{path}:{i}: {line.strip()[:80]}")
    return (not findings), findings
